name: check for pull request into master

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: x86
          python-version: 3.8
          cache: pip

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: run scons
        run: scons

