name: Build and release for official

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    uses: ./.github/workflows/testAndBuild.yml
    with:
      official_release: true

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ./

      - name: Deploy to GitHub
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.repository.name }} official release
          draft: true
          files: |
            ./${{ github.event.repository.name }}-*.zip
            ./*-*.nvda-addon
            ./${{ github.event.repository.name }}-*.json

  error_notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ failure() }}
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Github actions build failed! <${{ github.server_url }}/${{ github.repository }}|${{ github.event.repository.name }}>のofficial releaseビルドが失敗しました。\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|対象のrun>お確認し、対応着手時・完了後は、本チャンネルにて経緯を報告ください。"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

